/**
 * `content:build` step 10 (platform design §3.6 step 4; decision 5): write `.generated/`. Every
 * file is rewritten each run, `code/` is pruned of stale bundles, and keys are sorted, so the
 * output depends only on the content. Data is embedded as `JSON.parse(<string>)`: no object
 * literal for TypeScript to infer, no JSON import for the bundler to trace.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type { Catalog } from '@/lib/content/catalog-types'
import type { CodeBundle } from '@/lib/content/code-tokens'
import { parseItemId } from '@/lib/content/schemas/ids'

export type EmitInput = {
  repoRoot: string
  outDir: string
  catalog: Catalog
  /** MDX key (a lesson ID or `<problem ID>#note`) → the absolute path of its `.mdx` file. */
  mdx: Readonly<Record<string, string>>
  /** Item ID → its highlighted code. */
  code: Readonly<Record<string, CodeBundle>>
}

const GENERATED = '// Generated by `pnpm content:build` (platform design §3.6) — do not edit.'
const CODE_DIR = 'code'

const compareNames = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

const sortedEntries = <T>(record: Readonly<Record<string, T>>): [string, T][] =>
  Object.entries(record).sort(([a], [b]) => compareNames(a, b))

/** A module specifier from `fromDir` to `target`: relative, `/`-separated, starting with `.`. */
function specifier(fromDir: string, target: string): string {
  const relative = path.relative(fromDir, target).split(path.sep).join('/')
  return relative.startsWith('.') ? relative : `./${relative}`
}

/** A string literal that evaluates to `value` serialised as JSON. */
const jsonString = (value: unknown): string => JSON.stringify(JSON.stringify(value))

/** `{}`, or one `key: value,` line per entry. */
function objectLiteral(entries: readonly [string, string][]): string {
  if (entries.length === 0) return '{}'
  const lines = entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${value},`)
  return ['{', ...lines, '}'].join('\n')
}

/** `code/<trackId>/<localId>.ts` for an item ID. */
function bundlePath(itemId: string): string {
  const parsed = parseItemId(itemId)
  if (parsed === null) throw new Error(`no code bundle path for ${itemId}`)
  return `${CODE_DIR}/${parsed.trackId}/${parsed.localId}.ts`
}

/** Delete files under `dir` that are not in `keep` (paths relative to `root`), then empty folders. */
function prune(root: string, dir: string, keep: ReadonlySet<string>): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      prune(root, abs, keep)
      if (readdirSync(abs).length === 0) rmSync(abs, { recursive: true })
    } else if (!keep.has(path.relative(root, abs).split(path.sep).join('/'))) {
      rmSync(abs)
    }
  }
}

/** Write every generated file; returns their paths relative to `outDir`, sorted. */
export function emitGenerated(input: EmitInput): string[] {
  const { outDir, repoRoot, catalog } = input
  const moduleIn = (dir: string, target: string) =>
    specifier(path.join(outDir, dir), path.join(repoRoot, target))
  const files = new Map<string, string>()

  files.set('catalog.json', `${JSON.stringify(catalog, null, 2)}\n`)
  files.set(
    'catalog.ts',
    [
      GENERATED,
      `import type { Catalog } from '${moduleIn('.', 'lib/content/catalog-types')}'`,
      '',
      `export const CATALOG: Catalog = JSON.parse(${jsonString(catalog)})`,
      '',
    ].join('\n'),
  )

  const mdxLoaders = sortedEntries(input.mdx).map(([key, file]): [string, string] => [
    key,
    `() => import(${JSON.stringify(specifier(outDir, file))})`,
  ])
  files.set(
    'mdx.ts',
    [
      // TypeScript 6 no longer loads @types/* on its own; this declares `*.mdx` modules.
      '/// <reference types="mdx" />',
      GENERATED,
      "import type { MDXContent } from 'mdx/types'",
      '',
      `export const MDX_LOADERS: Readonly<Record<string, () => Promise<{ default: MDXContent }>>> = ${objectLiteral(mdxLoaders)}`,
      '',
    ].join('\n'),
  )

  const bundles = sortedEntries(input.code).map(([itemId, bundle]) => {
    const file = bundlePath(itemId)
    const dir = path.posix.dirname(file)
    files.set(
      file,
      [
        GENERATED,
        `import type { CodeBundle } from '${moduleIn(dir, 'lib/content/code-tokens')}'`,
        '',
        `const bundle: CodeBundle = JSON.parse(${jsonString(bundle)})`,
        'export default bundle',
        '',
      ].join('\n'),
    )
    return [itemId, `() => import(${JSON.stringify(`./${file.replace(/\.ts$/, '')}`)})`] as [
      string,
      string,
    ]
  })
  files.set(
    'code.ts',
    [
      GENERATED,
      `import type { CodeBundle } from '${moduleIn('.', 'lib/content/code-tokens')}'`,
      '',
      `export const CODE_LOADERS = ${objectLiteral(bundles)} satisfies Record<string, () => Promise<{ default: CodeBundle }>>`,
      '',
    ].join('\n'),
  )

  for (const [file, text] of files) {
    const abs = path.join(outDir, file)
    mkdirSync(path.dirname(abs), { recursive: true })
    writeFileSync(abs, text)
  }
  const codeDir = path.join(outDir, CODE_DIR)
  mkdirSync(codeDir, { recursive: true })
  prune(outDir, codeDir, new Set(files.keys()))

  return [...files.keys()].sort(compareNames)
}
