-- Generated by `pnpm db:fixtures` from lib/domain/time/fixtures.ts. Do not edit by hand.
-- [RF-1] parity: SQL public.local_day equals TypeScript localDay on the shared fixtures.
begin;
set client_min_messages = warning;
create extension if not exists pgtap with schema extensions;

select plan(23);

select is(public.local_day('2026-09-24T18:30:00Z'::timestamptz, 'Asia/Ho_Chi_Minh', '04:00'::time), '2026-09-24'::date, 'RF-1: 01:30 counts for the previous day');
select is(public.local_day('2026-09-24T18:30:00Z'::timestamptz, 'Asia/Saigon', '04:00'::time), '2026-09-24'::date, 'legacy alias (ICU''s name for VN) — SF8');
select is(public.local_day('2026-09-24T21:00:00Z'::timestamptz, 'Asia/Saigon', '04:00'::time), '2026-09-25'::date, 'legacy alias at the day start — SF8');
select is(public.local_day('2026-09-24T21:00:00Z'::timestamptz, 'Asia/Ho_Chi_Minh', '04:00'::time), '2026-09-25'::date, 'the day start itself is the new day');
select is(public.local_day('2026-09-24T20:59:59Z'::timestamptz, 'Asia/Ho_Chi_Minh', '04:00'::time), '2026-09-24'::date, 'one second before the day start');
select is(public.local_day('2026-09-24T17:00:00Z'::timestamptz, 'Asia/Ho_Chi_Minh', '00:00'::time), '2026-09-25'::date, 'midnight day start');
select is(public.local_day('2026-09-25T04:59:00Z'::timestamptz, 'Asia/Ho_Chi_Minh', '12:00'::time), '2026-09-24'::date, 'latest allowed day start, before');
select is(public.local_day('2026-09-25T05:00:00Z'::timestamptz, 'Asia/Ho_Chi_Minh', '12:00'::time), '2026-09-25'::date, 'latest allowed day start, at');
select is(public.local_day('2026-09-24T06:00:00Z'::timestamptz, 'America/St_Johns', '04:00'::time), '2026-09-23'::date, 'half-hour offset (NDT −2:30)');
select is(public.local_day('2026-01-15T07:30:00Z'::timestamptz, 'America/St_Johns', '04:00'::time), '2026-01-15'::date, 'half-hour offset (NST −3:30)');
select is(public.local_day('2026-03-08T07:30:00Z'::timestamptz, 'America/New_York', '04:00'::time), '2026-03-07'::date, 'spring forward, 03:30 EDT');
select is(public.local_day('2026-03-08T08:00:00Z'::timestamptz, 'America/New_York', '04:00'::time), '2026-03-08'::date, 'spring forward, 04:00 EDT');
select is(public.local_day('2026-11-01T08:30:00Z'::timestamptz, 'America/New_York', '04:00'::time), '2026-10-31'::date, 'fall back, 03:30 EST');
select is(public.local_day('2026-11-01T09:00:00Z'::timestamptz, 'America/New_York', '04:00'::time), '2026-11-01'::date, 'fall back, 04:00 EST');
select is(public.local_day('2026-09-24T22:00:00Z'::timestamptz, 'Asia/Kolkata', '04:00'::time), '2026-09-24'::date, '+5:30');
select is(public.local_day('2026-09-24T22:00:00Z'::timestamptz, 'Asia/Kolkata', '03:30'::time), '2026-09-25'::date, '+5:30, half-hour day start');
select is(public.local_day('2026-09-24T22:15:00Z'::timestamptz, 'Asia/Kathmandu', '04:00'::time), '2026-09-25'::date, '+5:45');
select is(public.local_day('2026-09-24T14:00:00Z'::timestamptz, 'Pacific/Kiritimati', '04:00'::time), '2026-09-25'::date, '+14');
select is(public.local_day('2026-09-25T14:59:00Z'::timestamptz, 'Pacific/Pago_Pago', '04:00'::time), '2026-09-24'::date, '−11');
select is(public.local_day('2028-02-29T23:30:00Z'::timestamptz, 'Europe/London', '00:00'::time), '2028-02-29'::date, 'leap day');
select is(public.local_day('2028-03-01T03:00:00Z'::timestamptz, 'Europe/London', '04:00'::time), '2028-02-29'::date, 'after a leap day');
select is(public.local_day('2026-12-31T18:59:59Z'::timestamptz, 'Asia/Tokyo', '04:00'::time), '2026-12-31'::date, 'year boundary, before');
select is(public.local_day('2026-12-31T19:00:00Z'::timestamptz, 'Asia/Tokyo', '04:00'::time), '2027-01-01'::date, 'year boundary, at');

select * from finish();
rollback;
