/**
 * Go runner (Part B-M3 decision 19): a generated `main_harness.go` switches on the case index and
 * calls the solution with literal arguments (`goLiteral`, 3.5a), then prints
 * `json.Marshal(harnessNormalize(result))` (the static `normalize.go`: nil slices → `[]`, fix 8).
 * Built once with cgo off (fix 6), no module proxy, the local toolchain only, and the build cache
 * under the work root.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { TestsFile } from '@/lib/content/schemas/tests'
import { SOLUTION_FILES } from '../discover'
import { goLiteral } from '../literals'
import {
  caseArguments,
  caseName,
  COMPILE_TIMEOUT_MS,
  functionCall,
  modeOf,
  noCases,
  signatureTargets,
  type Harness,
} from './harness'

const STATIC_DIR = join(import.meta.dirname, 'go')
const SOLUTION = SOLUTION_FILES.go
const GO_MOD = 'module verify\n\ngo 1.22\n'
const MAIN_STUB = 'package main\n\nfunc main() {}\n'

/** `main_harness.go` for a `function` signature. */
export function generateGoHarness(tests: TestsFile): string {
  const call = functionCall(tests)
  const lines = [
    '// Generated by content-verify (tools/content-verify/runners/go.ts).',
    'package main',
    '',
    'import (',
    '\t"encoding/json"',
    '\t"fmt"',
    '\t"os"',
    '\t"strconv"',
    ')',
    '',
    'func main() {',
    '\trealStdout := os.Stdout',
    "\tos.Stdout = os.Stderr // the solution's own prints must not corrupt the JSON result",
    '\tcaseIndex, err := strconv.Atoi(os.Args[1])',
    '\tif err != nil {',
    '\t\tfmt.Fprintln(os.Stderr, err)',
    '\t\tos.Exit(2)',
    '\t}',
    '\tvar caseResult any',
    '\tswitch caseIndex {',
  ]
  tests.cases.forEach((_, index) => {
    const values = caseArguments(tests, index)
    lines.push(`\tcase ${index}: // ${caseName(tests, index)}`)
    call.params.forEach((param, position) => {
      lines.push(`\t\targ${position} := ${goLiteral(values[position], param.type)}`)
    })
    const invocation = `${call.name}(${call.params.map((_, position) => `arg${position}`).join(', ')})`
    if (call.output !== null) {
      lines.push(`\t\t${invocation}`, `\t\tcaseResult = arg${call.output}`)
    } else if (call.returnsVoid) {
      lines.push(`\t\t${invocation}`)
    } else {
      lines.push(`\t\tcaseResult = ${invocation}`)
    }
  })
  lines.push(
    '\tdefault:',
    '\t\tfmt.Fprintln(os.Stderr, "no case", caseIndex)',
    '\t\tos.Exit(2)',
    '\t}',
    '\tencoded, err := json.Marshal(harnessNormalize(caseResult))',
    '\tif err != nil {',
    '\t\tfmt.Fprintln(os.Stderr, err)',
    '\t\tos.Exit(1)',
    '\t}',
    '\trealStdout.Write(encoded)',
    '}',
    '',
  )
  return lines.join('\n')
}

const stripComments = (source: string): string =>
  source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')

const capitalise = (name: string): string => name.charAt(0).toUpperCase() + name.slice(1)

/** The compile-only signature check: `func <name>(` for a function, or `type <Class> struct`,
 * `func Constructor(` and a `(*<Class>)` method per capitalised method name (LeetCode's Go). */
export function goSignatureIssues(source: string, tests: TestsFile): string[] {
  const code = stripComments(source)
  const { signature } = tests
  const issues: string[] = []
  if (signature.kind !== 'design-class') {
    if (!new RegExp(`\\bfunc\\s+${signature.name}\\s*\\(`).test(code)) {
      issues.push(`${SOLUTION}: no func ${signature.name}(`)
    }
    return issues
  }
  const { className, methods } = signatureTargets(tests)
  if (!new RegExp(`\\btype\\s+${className}\\s+struct\\b`).test(code)) {
    issues.push(`${SOLUTION}: no type ${className} struct`)
  }
  if (!/\bfunc\s+Constructor\s*\(/.test(code)) issues.push(`${SOLUTION}: no func Constructor(`)
  for (const method of methods.map(capitalise)) {
    const receiver = `\\bfunc\\s*\\(\\s*(?:\\w+\\s+)?\\*?\\s*${className}\\s*\\)\\s*${method}\\s*\\(`
    if (!new RegExp(receiver).test(code)) {
      issues.push(`${SOLUTION}: no method (*${className}) ${method}(`)
    }
  }
  return issues
}

export const goHarness: Harness = {
  lang: 'go',
  prepare(problem, workDir) {
    const workRoot = dirname(workDir)
    const sharedDirs = [join(workRoot, 'go-cache'), join(workRoot, 'go-path')]
    for (const dir of sharedDirs) mkdirSync(dir, { recursive: true })
    const [cache = '', path = ''] = sharedDirs
    const env = {
      CGO_ENABLED: '0',
      GOPROXY: 'off',
      GOTOOLCHAIN: 'local',
      GOFLAGS: '-mod=mod',
      GOENV: 'off',
      GOWORK: 'off',
      GOCACHE: cache,
      GOPATH: path,
    }
    copyFileSync(join(problem.dir, SOLUTION), join(workDir, SOLUTION))
    writeFileSync(join(workDir, 'go.mod'), GO_MOD)

    if (modeOf(problem) === 'compile-only') {
      const source = readFileSync(join(workDir, SOLUTION), 'utf8')
      if (!/^func\s+main\s*\(/m.test(stripComments(source))) {
        writeFileSync(join(workDir, 'main_stub.go'), MAIN_STUB)
      }
      return {
        compile: [],
        warmUp: [],
        runCase: noCases,
        compileOnly: [
          { cmd: 'go', args: ['vet', '.'], cwd: workDir, env, timeoutMs: COMPILE_TIMEOUT_MS.go },
        ],
        signatureIssues: goSignatureIssues(source, problem.tests),
        sharedDirs,
      }
    }
    copyFileSync(join(STATIC_DIR, 'normalize.go'), join(workDir, 'normalize.go'))
    writeFileSync(join(workDir, 'main_harness.go'), generateGoHarness(problem.tests))
    const binary = join(workDir, 'bin')
    return {
      compile: [
        {
          cmd: 'go',
          args: ['build', '-o', 'bin', '.'],
          cwd: workDir,
          env,
          timeoutMs: COMPILE_TIMEOUT_MS.go,
        },
      ],
      // Not a case index: the harness exits at once. Only the first exec's OS scan matters.
      warmUp: [
        { cmd: binary, args: ['warm-up'], cwd: workDir, timeoutMs: COMPILE_TIMEOUT_MS.warmUp },
      ],
      runCase: (index) => ({
        cmd: binary,
        args: [String(index)],
        cwd: workDir,
        timeoutMs: problem.tests.timeoutMs,
      }),
      compileOnly: [],
      signatureIssues: [],
      sharedDirs,
    }
  },
}
