import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { testsFileSchema } from '@/lib/content/schemas/tests'
import { discoverProblems, type ProblemUnderTest } from '../discover'
import { generateGoHarness, goHarness } from './go'
import { generateJavaMain, javaHarness } from './java'
import { pythonHarness } from './python'

const TWO_SUM = testsFileSchema.parse({
  signature: {
    kind: 'function',
    name: 'twoSum',
    params: { nums: 'int[]', target: 'int' },
    returns: 'int[]',
  },
  compare: 'unordered',
  cases: [
    { name: 'example-1', input: { nums: [2, 7, 11, 15], target: 9 }, expected: [0, 1] },
    { name: 'example-2', input: { nums: [3, 2, 4], target: 6 }, expected: [1, 2] },
    { name: 'duplicates', input: { nums: [3, 3], target: 6 }, expected: [0, 1] },
    { name: 'negatives', input: { nums: [-1, -2, -3, -4, -5], target: -8 }, expected: [2, 4] },
  ],
})

const FIXTURES = join(import.meta.dirname, '..', '__fixtures__', 'tracks')
const fixture = (id: string): ProblemUnderTest => {
  const problem = discoverProblems(FIXTURES, { ids: [id] }).problems[0]
  if (problem === undefined) throw new Error(`fixture ${id} missing`)
  return problem
}

describe('generateJavaMain — two-sum', () => {
  it('switches on the case index, one method per case with literal arguments', () => {
    expect(generateJavaMain(TWO_SUM))
      .toBe(`// Generated by content-verify (tools/content-verify/runners/java.ts).
public class HarnessMain {
    public static void main(String[] args) {
        java.io.PrintStream stdout = System.out;
        System.setOut(System.err); // the solution's own prints must not corrupt the JSON result
        Object result = switch (Integer.parseInt(args[0])) {
            case 0 -> case0();
            case 1 -> case1();
            case 2 -> case2();
            case 3 -> case3();
            default -> throw new IllegalArgumentException("no case " + args[0]);
        };
        stdout.print(HarnessJson.write(result));
        stdout.flush();
    }

    // example-1
    private static Object case0() {
        int[] arg0 = new int[]{2,7,11,15};
        int arg1 = 9;
        return new Solution().twoSum(arg0, arg1);
    }

    // example-2
    private static Object case1() {
        int[] arg0 = new int[]{3,2,4};
        int arg1 = 6;
        return new Solution().twoSum(arg0, arg1);
    }

    // duplicates
    private static Object case2() {
        int[] arg0 = new int[]{3,3};
        int arg1 = 6;
        return new Solution().twoSum(arg0, arg1);
    }

    // negatives
    private static Object case3() {
        int[] arg0 = new int[]{-1,-2,-3,-4,-5};
        int arg1 = -8;
        return new Solution().twoSum(arg0, arg1);
    }
}
`)
  })

  it('returns the mutated argument for an in-place signature', () => {
    const source = generateJavaMain(fixture('demo:lc-9006').tests)
    expect(source).toContain(`    // example-1
    private static Object case0() {
        int[] arg0 = new int[]{1,2,3};
        new Solution().reverse(arg0);
        return arg0;
    }`)
  })
})

describe('generateGoHarness — two-sum', () => {
  it('switches on the case index with literal arguments and normalises the result', () => {
    expect(generateGoHarness(TWO_SUM))
      .toBe(`// Generated by content-verify (tools/content-verify/runners/go.ts).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
)

func main() {
	realStdout := os.Stdout
	os.Stdout = os.Stderr // the solution's own prints must not corrupt the JSON result
	caseIndex, err := strconv.Atoi(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	var caseResult any
	switch caseIndex {
	case 0: // example-1
		arg0 := []int{2,7,11,15}
		arg1 := 9
		caseResult = twoSum(arg0, arg1)
	case 1: // example-2
		arg0 := []int{3,2,4}
		arg1 := 6
		caseResult = twoSum(arg0, arg1)
	case 2: // duplicates
		arg0 := []int{3,3}
		arg1 := 6
		caseResult = twoSum(arg0, arg1)
	case 3: // negatives
		arg0 := []int{-1,-2,-3,-4,-5}
		arg1 := -8
		caseResult = twoSum(arg0, arg1)
	default:
		fmt.Fprintln(os.Stderr, "no case", caseIndex)
		os.Exit(2)
	}
	encoded, err := json.Marshal(harnessNormalize(caseResult))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	realStdout.Write(encoded)
}
`)
  })

  it('reports the mutated argument for an in-place signature', () => {
    expect(generateGoHarness(fixture('demo:lc-9006').tests)).toContain(`	case 0: // example-1
		arg0 := []int{1,2,3}
		reverse(arg0)
		caseResult = arg0
`)
  })
})

describe('prepare', () => {
  let root: string
  let workDir: string

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'cv-harness-'))
    workDir = join(root, 'unit')
    mkdirSync(workDir)
  })

  afterEach(() => {
    rmSync(root, { recursive: true, force: true })
  })

  it('python: copies runner.py and check.py into the work dir (fix 6) and runs the case from stdin', () => {
    const prepared = pythonHarness.prepare(fixture('demo:lc-9006'), workDir)
    for (const file of ['solution.py', 'runner.py', 'check.py']) {
      expect(existsSync(join(workDir, file))).toBe(true)
    }
    expect(prepared.compile).toEqual([
      {
        cmd: 'python',
        args: [
          '-I',
          '-B',
          'check.py',
          'solution.py',
          '{"className":"Solution","methods":["reverse"]}',
        ],
        cwd: workDir,
        timeoutMs: 30_000,
      },
    ])
    expect(prepared.runCase(2)).toEqual({
      cmd: 'python',
      args: ['-I', '-B', 'runner.py'],
      cwd: workDir,
      stdin: '{"file":"solution.py","method":"reverse","args":[[]],"output":0}',
      timeoutMs: 2000,
    })
  })

  it('python: checks a design class for every method (compile-only)', () => {
    const prepared = pythonHarness.prepare(fixture('demo:lc-9004'), workDir)
    expect(prepared.compileOnly[0]?.args.at(-1)).toBe(
      '{"className":"MinStack","methods":["push","pop","top","getMin"]}',
    )
    expect(prepared.signatureIssues).toEqual([])
  })

  it('java: compiles once with -proc:none (fix 6) and runs HarnessMain <index>', () => {
    const prepared = javaHarness.prepare(fixture('demo:lc-9001'), workDir)
    for (const file of ['Solution.java', 'HarnessJson.java', 'HarnessMain.java']) {
      expect(existsSync(join(workDir, file))).toBe(true)
    }
    expect(prepared.compile).toEqual([
      {
        cmd: 'javac',
        args: [
          '--release',
          '21',
          '-proc:none',
          '-encoding',
          'UTF-8',
          '-d',
          'out',
          'Solution.java',
          'HarnessJson.java',
          'HarnessMain.java',
        ],
        cwd: workDir,
        timeoutMs: 60_000,
      },
    ])
    expect(prepared.runCase(3)).toEqual({
      cmd: 'java',
      args: ['-Xss64m', '-Xmx512m', '-cp', 'out', 'HarnessMain', '3'],
      cwd: workDir,
      timeoutMs: 2000,
    })
  })

  it('java: compile-only compiles the solution alone and checks the class and methods', () => {
    const prepared = javaHarness.prepare(fixture('demo:lc-9004'), workDir)
    expect(prepared.compileOnly).toEqual([
      {
        cmd: 'javac',
        args: ['--release', '21', '-proc:none', '-encoding', 'UTF-8', '-d', 'out', 'Solution.java'],
        cwd: workDir,
        timeoutMs: 60_000,
      },
    ])
    expect(prepared.signatureIssues).toEqual([])
    expect(existsSync(join(workDir, 'HarnessMain.java'))).toBe(false)
  })

  it('java: a missing method declaration is a signature issue (a call does not count)', () => {
    const problem = fixture('demo:lc-9004')
    const dir = join(root, 'problem')
    mkdirSync(dir)
    writeFileSync(
      join(dir, 'Solution.java'),
      readFileSync(join(problem.dir, 'Solution.java'), 'utf8').replace(
        'public int getMin() {\n        return minimums.peek();\n    }',
        '',
      ) + '\nclass Other { void use(MinStack s) { s.getMin(); } }\n',
    )
    const prepared = javaHarness.prepare({ ...problem, dir }, workDir)
    expect(prepared.signatureIssues).toEqual(['Solution.java: no method getMin(…) { … }'])
  })

  it('go: builds with CGO_ENABLED=0 (fix 6), no proxy, local toolchain, caches under the work root', () => {
    const prepared = goHarness.prepare(fixture('demo:lc-9007'), workDir)
    for (const file of ['solution.go', 'normalize.go', 'main_harness.go', 'go.mod']) {
      expect(existsSync(join(workDir, file))).toBe(true)
    }
    expect(readFileSync(join(workDir, 'go.mod'), 'utf8')).toBe('module verify\n\ngo 1.22\n')
    const env = {
      CGO_ENABLED: '0',
      GOPROXY: 'off',
      GOTOOLCHAIN: 'local',
      GOFLAGS: '-mod=mod -buildvcs=false',
      GOENV: 'off',
      GOWORK: 'off',
      GOCACHE: join(root, 'go-cache'),
      GOPATH: join(root, 'go-path'),
    }
    expect(prepared.compile).toEqual([
      { cmd: 'go', args: ['build', '-o', 'bin', '.'], cwd: workDir, env, timeoutMs: 120_000 },
    ])
    expect(prepared.sharedDirs).toEqual([join(root, 'go-cache'), join(root, 'go-path')])
    // one untimed run after the build: macOS scans a fresh binary on its first exec (~0.5 s)
    expect(prepared.warmUp).toEqual([
      { cmd: join(workDir, 'bin'), args: ['warm-up'], cwd: workDir, timeoutMs: 10_000 },
    ])
    expect(prepared.runCase(0)).toEqual({
      cmd: join(workDir, 'bin'),
      args: ['0'],
      cwd: workDir,
      timeoutMs: 2000,
    })
  })

  it('go: compile-only adds a main stub, vets, and checks the type, Constructor and methods', () => {
    const prepared = goHarness.prepare(fixture('demo:lc-9004'), workDir)
    expect(readFileSync(join(workDir, 'main_stub.go'), 'utf8')).toBe(
      'package main\n\nfunc main() {}\n',
    )
    expect(existsSync(join(workDir, 'main_harness.go'))).toBe(false)
    expect(prepared.compileOnly.map((command) => [command.cmd, ...command.args])).toEqual([
      ['go', 'vet', '.'],
    ])
    expect(prepared.compileOnly[0]?.env?.CGO_ENABLED).toBe('0')
    expect(prepared.signatureIssues).toEqual([])
  })

  it.each([
    ['python', pythonHarness, 'solution.py'],
    ['java', javaHarness, 'Solution.java'],
    ['go', goHarness, 'solution.go'],
  ] as const)(
    '%s: refuses a symlinked solution instead of reading through it',
    (_, harness, file) => {
      const problem = fixture('demo:lc-9001')
      const dir = join(root, 'problem')
      mkdirSync(dir)
      symlinkSync(join(problem.dir, file), join(dir, file))
      expect(() => harness.prepare({ ...problem, dir }, workDir)).toThrow(
        `${file} is not a regular file (a symlink?); it is never followed`,
      )
    },
  )

  it('go: reports a missing Constructor or method', () => {
    const problem = fixture('demo:lc-9004')
    const dir = join(root, 'problem')
    mkdirSync(dir)
    writeFileSync(
      join(dir, 'solution.go'),
      readFileSync(join(problem.dir, 'solution.go'), 'utf8')
        .replace('func Constructor()', 'func NewMinStack()')
        .replace('func (this *MinStack) GetMin()', 'func (this *MinStack) Minimum()'),
    )
    const prepared = goHarness.prepare({ ...problem, dir }, workDir)
    expect(prepared.signatureIssues).toEqual([
      'solution.go: no func Constructor(',
      'solution.go: no method (*MinStack) GetMin(',
    ])
  })
})
