/**
 * Java runner (Part B-M3 decision 19): a generated `HarnessMain.java` switches on the case index
 * and calls the solution with literal arguments (`javaLiteral`, 3.5a); the static
 * `HarnessJson.java` prints the result. The `Harness` prefix keeps both clear of a solution's own
 * helper classes (`Main`, `Json`). One method per case keeps every case under the JVM's 64 KB
 * method limit. Compiled once with `-proc:none` (fix 6: no annotation processor runs).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { TestsFile } from '@/lib/content/schemas/tests'
import { SOLUTION_FILES } from '../discover'
import { javaLiteral, javaType } from '../literals'
import type { Command } from '../sandbox'
import {
  caseArguments,
  caseName,
  copyRegularFile,
  COMPILE_TIMEOUT_MS,
  functionCall,
  modeOf,
  noCases,
  signatureTargets,
  type Harness,
} from './harness'

const STATIC_DIR = join(import.meta.dirname, 'java')
const SOLUTION = SOLUTION_FILES.java
const JAVAC_FLAGS = ['--release', '21', '-proc:none', '-encoding', 'UTF-8', '-d', 'out']
const JAVA_FLAGS = ['-Xss64m', '-Xmx512m', '-cp', 'out']

const MAIN = 'HarnessMain'
const JSON_CLASS = 'HarnessJson'

/** `HarnessMain.java` for a `function` signature. */
export function generateJavaMain(tests: TestsFile): string {
  const call = functionCall(tests)
  const lines = [
    '// Generated by content-verify (tools/content-verify/runners/java.ts).',
    `public class ${MAIN} {`,
    '    public static void main(String[] args) {',
    '        java.io.PrintStream stdout = System.out;',
    "        System.setOut(System.err); // the solution's own prints must not corrupt the JSON result",
    '        Object result = switch (Integer.parseInt(args[0])) {',
    ...tests.cases.map((_, index) => `            case ${index} -> case${index}();`),
    '            default -> throw new IllegalArgumentException("no case " + args[0]);',
    '        };',
    `        stdout.print(${JSON_CLASS}.write(result));`,
    '        stdout.flush();',
    '    }',
  ]
  tests.cases.forEach((_, index) => {
    const values = caseArguments(tests, index)
    lines.push('', `    // ${caseName(tests, index)}`, `    private static Object case${index}() {`)
    call.params.forEach((param, position) => {
      const literal = javaLiteral(values[position], param.type)
      lines.push(`        ${javaType(param.type)} arg${position} = ${literal};`)
    })
    const args = call.params.map((_, position) => `arg${position}`).join(', ')
    const invocation = `new Solution().${call.name}(${args})`
    if (call.output !== null) {
      lines.push(`        ${invocation};`, `        return arg${call.output};`)
    } else if (call.returnsVoid) {
      lines.push(`        ${invocation};`, '        return null;')
    } else {
      lines.push(`        return ${invocation};`)
    }
    lines.push('    }')
  })
  lines.push('}', '')
  return lines.join('\n')
}

const stripComments = (source: string): string =>
  source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')

/** The compile-only signature check: `class <Name>` and a declaration `<method>(…) {` for each
 * method (a call such as `stack.push(x);` does not count). */
export function javaSignatureIssues(source: string, tests: TestsFile): string[] {
  const code = stripComments(source)
  const { className, methods } = signatureTargets(tests)
  const issues: string[] = []
  if (!new RegExp(`\\bclass\\s+${className}\\b`).test(code)) {
    issues.push(`${SOLUTION}: no class ${className}`)
  }
  for (const method of methods) {
    const declaration = new RegExp(`\\b${method}\\s*\\([^()]*\\)\\s*(?:throws\\s+[\\w.,\\s]+)?\\{`)
    if (!declaration.test(code)) issues.push(`${SOLUTION}: no method ${method}(…) { … }`)
  }
  return issues
}

const javac = (workDir: string, files: string[]): Command => ({
  cmd: 'javac',
  args: [...JAVAC_FLAGS, ...files],
  cwd: workDir,
  timeoutMs: COMPILE_TIMEOUT_MS.javac,
})

export const javaHarness: Harness = {
  lang: 'java',
  prepare(problem, workDir) {
    copyRegularFile(join(problem.dir, SOLUTION), join(workDir, SOLUTION))
    mkdirSync(join(workDir, 'out'), { recursive: true })

    if (modeOf(problem) === 'compile-only') {
      const source = readFileSync(join(workDir, SOLUTION), 'utf8')
      return {
        compile: [],
        warmUp: [],
        runCase: noCases,
        compileOnly: [javac(workDir, [SOLUTION])],
        signatureIssues: javaSignatureIssues(source, problem.tests),
        sharedDirs: [],
      }
    }
    copyRegularFile(join(STATIC_DIR, `${JSON_CLASS}.java`), join(workDir, `${JSON_CLASS}.java`))
    writeFileSync(join(workDir, `${MAIN}.java`), generateJavaMain(problem.tests))
    return {
      compile: [javac(workDir, [SOLUTION, `${JSON_CLASS}.java`, `${MAIN}.java`])],
      warmUp: [],
      runCase: (index) => ({
        cmd: 'java',
        args: [...JAVA_FLAGS, MAIN, String(index)],
        cwd: workDir,
        timeoutMs: problem.tests.timeoutMs,
      }),
      compileOnly: [],
      signatureIssues: [],
      sharedDirs: [],
    }
  },
}
