/**
 * Java runner (Part B-M3 decision 19): a generated `HarnessMain.java` switches on the case index
 * and calls the solution with literal arguments (`javaLiteral`, 3.5a); the static
 * `HarnessJson.java` prints the result. The `Harness` prefix keeps both clear of a solution's own
 * helper classes (`Main`, `Json`). One method per case keeps every case under the JVM's 64 KB
 * method limit. Compiled once with `-proc:none` (fix 6: no annotation processor runs). The
 * structured kinds (M3b) add LeetCode's `ListNode` / `TreeNode` / `Node` classes and their codecs
 * (`HarnessLists`, `HarnessTrees`, `HarnessGraphs`, `HarnessRandomLists`) in the default package.
 * A design class (M3c) gets one method per case that runs its operations on one instance.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Structure, TestsFile } from '@/lib/content/schemas/tests'
import { SOLUTION_FILES } from '../discover'
import { javaArgument, JAVA_STRUCTURES, javaStructureLiteral } from '../literals'
import type { Command } from '../sandbox'
import {
  callStructures,
  caseArguments,
  caseName,
  copyRegularFile,
  COMPILE_TIMEOUT_MS,
  designOperations,
  functionCall,
  modeOf,
  noCases,
  reportedType,
  signatureTargets,
  type FunctionCall,
  type Harness,
} from './harness'

const STATIC_DIR = join(import.meta.dirname, 'java')
const SOLUTION = SOLUTION_FILES.java
const JAVAC_FLAGS = ['--release', '21', '-proc:none', '-encoding', 'UTF-8', '-d', 'out']
const JAVA_FLAGS = ['-Xss64m', '-Xmx512m', '-cp', 'out']

const MAIN = 'HarnessMain'
const JSON_CLASS = 'HarnessJson'

/** `HarnessMain.java` for a `function` or structured (M3b) signature: structures are decoded from
 * their `tests.yaml` encoding before the call and a structure result is encoded back. With the
 * solution's `source`, an array parameter the solution declares as a `List<…>` is passed as one
 * (`javaArgument`). */
export function generateJavaMain(tests: TestsFile, source?: string): string {
  if (tests.signature.kind === 'design-class') return generateJavaDesignMain(tests, source)
  const call = functionCall(tests)
  const declared = (source === undefined ? null : javaParameterTypes(source, call.name)) ?? []
  const lines = [
    '// Generated by content-verify (tools/content-verify/runners/java.ts).',
    `public class ${MAIN} {`,
    '    public static void main(String[] args) {',
    '        java.io.PrintStream stdout = System.out;',
    "        System.setOut(System.err); // the solution's own prints must not corrupt the JSON result",
    '        Object result = switch (Integer.parseInt(args[0])) {',
    ...tests.cases.map((_, index) => `            case ${index} -> case${index}();`),
    '            default -> throw new IllegalArgumentException("no case " + args[0]);',
    '        };',
    `        stdout.print(${JSON_CLASS}.write(result));`,
    '        stdout.flush();',
    '    }',
  ]
  tests.cases.forEach((_, index) => {
    const values = caseArguments(tests, index)
    lines.push('', `    // ${caseName(tests, index)}`, `    private static Object case${index}() {`)
    call.params.forEach((param, position) => {
      const arg =
        param.type.kind === 'structure'
          ? {
              type: JAVA_STRUCTURES[param.type.structure].type,
              expression: javaStructureLiteral(values[position], param.type.structure),
            }
          : javaArgument(values[position], param.type.type, declared[position] ?? null)
      lines.push(`        ${arg.type} arg${position} = ${arg.expression};`)
    })
    const copy = call.copyOf === null ? null : call.params[call.copyOf]?.type
    const copyCodec = copy?.kind === 'structure' ? JAVA_STRUCTURES[copy.structure].codec : null
    if (copyCodec !== null) {
      lines.push(`        java.util.Set<Node> inputs = ${copyCodec}.nodes(arg${call.copyOf});`)
    }
    const args = call.params.map((_, position) => `arg${position}`).join(', ')
    const invocation = `new Solution().${call.name}(${args})`
    const reported = reportedType(call)
    /** The printed value: a structure is encoded back to its tests.yaml form. */
    const encoded = (expression: string): string => {
      if (reported?.kind !== 'structure') return expression
      const { codec } = JAVA_STRUCTURES[reported.structure]
      if (copyCodec !== null) return `${codec}.encodeCopy(${expression}, inputs)`
      return `${codec}.${reported.structure === 'lists' ? 'encodeAll' : 'encode'}(${expression})`
    }
    if (call.output !== null) {
      lines.push(`        ${invocation};`, `        return ${encoded(`arg${call.output}`)};`)
    } else if (call.returns === null) {
      lines.push(`        ${invocation};`, '        return null;')
    } else {
      lines.push(`        return ${encoded(invocation)};`)
    }
    lines.push('    }')
  })
  lines.push('}', '')
  return lines.join('\n')
}

/** `HarnessMain.java` for a design class (M3c): each case constructs the class, calls the
 * operations in order and records each result as JSON when its operation returns (a later
 * operation may change a list it returned); `{ $result: n }` passes `result<n>`, whose type `var`
 * takes from the method. A throw names the operation. With the solution's `source`, an array
 * parameter declared as a `List<…>` gets one (`javaArgument`). */
function generateJavaDesignMain(tests: TestsFile, source?: string): string {
  const { signature } = tests
  if (signature.kind !== 'design-class') throw new Error('not a design class')
  const declaredCache = new Map<string, string[]>()
  const declared = (name: string): string[] => {
    let types = declaredCache.get(name)
    if (types === undefined) {
      types = (source === undefined ? null : javaParameterTypes(source, name)) ?? []
      declaredCache.set(name, types)
    }
    return types
  }
  const lines = [
    '// Generated by content-verify (tools/content-verify/runners/java.ts).',
    `public class ${MAIN} {`,
    '    private static int harnessOp = -1;',
    '    private static String harnessOpName = "";',
    '',
    '    public static void main(String[] args) {',
    '        java.io.PrintStream stdout = System.out;',
    "        System.setOut(System.err); // the solution's own prints must not corrupt the JSON result",
    '        String result;',
    '        try {',
    '            result = switch (Integer.parseInt(args[0])) {',
    ...tests.cases.map((_, index) => `                case ${index} -> case${index}();`),
    '                default -> throw new IllegalArgumentException("no case " + args[0]);',
    '            };',
    '        } catch (Throwable error) {',
    '            System.err.println("op " + harnessOp + " (" + harnessOpName + "): " + error);',
    '            error.printStackTrace();',
    '            System.exit(1);',
    '            return;',
    '        }',
    '        stdout.print(result);',
    '        stdout.flush();',
    '    }',
    '',
    '    private static void op(int index, String name) {',
    '        harnessOp = index;',
    '        harnessOpName = name;',
    '    }',
  ]
  tests.cases.forEach((_, index) => {
    const operations = designOperations(tests, index)
    lines.push(
      '',
      `    // ${caseName(tests, index)}`,
      `    private static String case${index}() {`,
      `        String[] results = new String[${operations.length}];`,
    )
    operations.forEach((operation, opIndex) => {
      const types = declared(operation.method ?? signature.className)
      const args = operation.args
        .map((arg, position) =>
          arg.kind === 'result'
            ? `result${arg.op}`
            : javaArgument(arg.value, arg.type, types[position] ?? null).expression,
        )
        .join(', ')
      lines.push(`        op(${opIndex}, ${JSON.stringify(operation.name)});`)
      if (operation.method === null) {
        lines.push(
          `        ${signature.className} harnessObject = new ${signature.className}(${args});`,
          `        results[${opIndex}] = "null";`,
        )
      } else if (operation.returns === null) {
        lines.push(
          `        harnessObject.${operation.method}(${args});`,
          `        results[${opIndex}] = "null";`,
        )
      } else {
        lines.push(
          `        var result${opIndex} = harnessObject.${operation.method}(${args});`,
          `        results[${opIndex}] = ${JSON_CLASS}.write(result${opIndex});`,
        )
      }
    })
    lines.push('        return "[" + String.join(",", results) + "]";', '    }')
  })
  lines.push('}', '')
  return lines.join('\n')
}

const stripComments = (source: string): string =>
  source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')

/** Splits `text` at the commas outside `<…>` (generic arguments). */
function splitTopLevel(text: string): string[] {
  const parts: string[] = []
  let depth = 0
  let current = ''
  for (const ch of text) {
    if (ch === '<') depth += 1
    if (ch === '>') depth -= 1
    if (ch === ',' && depth === 0) {
      parts.push(current)
      current = ''
    } else {
      current += ch
    }
  }
  if (current.trim() !== '') parts.push(current)
  return parts
}

/** The declared parameter types of `method`'s first declaration in `source` (comments ignored;
 * modifiers and annotations dropped), e.g. `['String', 'List<String>']`; `null` when there is no
 * declaration. */
export function javaParameterTypes(source: string, method: string): string[] | null {
  const declaration = new RegExp(
    `\\b${method}\\s*\\(([^()]*)\\)\\s*(?:throws\\s+[\\w.,\\s]+)?\\{`,
  ).exec(stripComments(source))
  if (declaration === null) return null
  return splitTopLevel(declaration[1] ?? '').map((parameter) =>
    parameter
      .replace(/@[\w.]+/g, ' ')
      .replace(/\bfinal\b/g, ' ')
      .trim()
      .replace(/\s+\w+$/, '')
      .trim(),
  )
}

/** The compile-only signature check: `class <Name>` and a declaration `<method>(…) {` for each
 * method (a call such as `stack.push(x);` does not count). */
export function javaSignatureIssues(source: string, tests: TestsFile): string[] {
  const code = stripComments(source)
  const { className, methods } = signatureTargets(tests)
  const issues: string[] = []
  if (!new RegExp(`\\bclass\\s+${className}\\b`).test(code)) {
    issues.push(`${SOLUTION}: no class ${className}`)
  }
  for (const method of methods) {
    const declaration = new RegExp(`\\b${method}\\s*\\([^()]*\\)\\s*(?:throws\\s+[\\w.,\\s]+)?\\{`)
    if (!declaration.test(code)) issues.push(`${SOLUTION}: no method ${method}(…) { … }`)
  }
  return issues
}

/** The static structure classes a call needs, as [source under runners/java, file name]. Graph
 * and random-pointer lists each have their own `Node`; a problem uses one of them. */
const JAVA_STRUCTURE_FILES: Readonly<Record<Structure, readonly [string, string][]>> = {
  list: [
    ['ListNode.java', 'ListNode.java'],
    ['HarnessLists.java', 'HarnessLists.java'],
  ],
  lists: [
    ['ListNode.java', 'ListNode.java'],
    ['HarnessLists.java', 'HarnessLists.java'],
  ],
  tree: [
    ['TreeNode.java', 'TreeNode.java'],
    ['HarnessTrees.java', 'HarnessTrees.java'],
  ],
  graph: [
    ['graph/Node.java', 'Node.java'],
    ['graph/HarnessGraphs.java', 'HarnessGraphs.java'],
  ],
  'random-list': [
    ['random-list/Node.java', 'Node.java'],
    ['random-list/HarnessRandomLists.java', 'HarnessRandomLists.java'],
  ],
}

function javaStructureFiles(call: FunctionCall): [string, string][] {
  const files = new Map<string, string>()
  for (const structure of callStructures(call)) {
    for (const [source, file] of JAVA_STRUCTURE_FILES[structure]) files.set(file, source)
  }
  return [...files].map(([file, source]) => [source, file])
}

const javac = (workDir: string, files: string[]): Command => ({
  cmd: 'javac',
  args: [...JAVAC_FLAGS, ...files],
  cwd: workDir,
  timeoutMs: COMPILE_TIMEOUT_MS.javac,
})

export const javaHarness: Harness = {
  lang: 'java',
  prepare(problem, workDir) {
    copyRegularFile(join(problem.dir, SOLUTION), join(workDir, SOLUTION))
    mkdirSync(join(workDir, 'out'), { recursive: true })

    if (modeOf(problem) === 'compile-only') {
      const source = readFileSync(join(workDir, SOLUTION), 'utf8')
      return {
        compile: [],
        warmUp: [],
        runCase: noCases,
        compileOnly: [javac(workDir, [SOLUTION])],
        signatureIssues: javaSignatureIssues(source, problem.tests),
        sharedDirs: [],
      }
    }
    copyRegularFile(join(STATIC_DIR, `${JSON_CLASS}.java`), join(workDir, `${JSON_CLASS}.java`))
    const structureFiles: string[] = []
    const structures =
      problem.tests.signature.kind === 'design-class'
        ? []
        : javaStructureFiles(functionCall(problem.tests))
    for (const [source, file] of structures) {
      copyRegularFile(join(STATIC_DIR, source), join(workDir, file))
      structureFiles.push(file)
    }
    const source = readFileSync(join(workDir, SOLUTION), 'utf8')
    writeFileSync(join(workDir, `${MAIN}.java`), generateJavaMain(problem.tests, source))
    return {
      compile: [
        javac(workDir, [SOLUTION, `${JSON_CLASS}.java`, ...structureFiles, `${MAIN}.java`]),
      ],
      warmUp: [],
      runCase: (index) => ({
        cmd: 'java',
        args: [...JAVA_FLAGS, MAIN, String(index)],
        cwd: workDir,
        timeoutMs: problem.tests.timeoutMs,
      }),
      compileOnly: [],
      signatureIssues: [],
      sharedDirs: [],
    }
  },
}
