-- Task 2.5: the append-only event log, the learner write quota and local_day (platform design
-- §4.1, §4.4, §4.5, §5.1; ADR-0030). apply_event / apply_system_event arrive in 2.5b.
-- Every function revokes PUBLIC explicitly (see 20260925000100: the per-schema default privilege
-- cannot remove PUBLIC's EXECUTE); schema-invariants (001) fails if one does not.

-- ---------------------------------------------------------------------------------------------
-- Functions shared with TypeScript. tools/db/sql-sync.test.ts reads the last
-- `create or replace function` of learner_event_types and rules_version across all migrations
-- and compares them with LEARNER_EVENT_TYPES and RULES_VERSION: change both sides together.
-- ---------------------------------------------------------------------------------------------

-- §4.7: the engine rules version (lib/domain/rules.ts RULES_VERSION). M4 bumps both together.
create or replace function public.rules_version() returns integer
language sql immutable set search_path = '' as $$
  select 1
$$;

-- §4.4: the types a learner may write (lib/domain/events.ts LEARNER_EVENT_TYPES).
create or replace function public.learner_event_types() returns text[]
language sql immutable set search_path = '' as $$
  select array[
    'block.checked_in',
    'item.result',
    'lesson.completed',
    'exercise.submitted',
    'prompt.completed',
    'item.skipped',
    'item.readded',
    'track.enrolled',
    'track.updated',
    'track.paused',
    'track.resumed',
    'track.removed',
    'track.reset',
    'schedule.changed',
    'settings.changed'
  ]::text[]
$$;

-- §5.1: the date part of (the wall-clock time of p_at in p_timezone, minus the day start).
-- [RF-1] 020-local-day-parity (generated by `pnpm db:fixtures`) checks it against TypeScript
-- localDay on the shared fixtures.
create or replace function public.local_day(
  p_at timestamptz, p_timezone text, p_day_starts_at time
) returns date
language sql stable set search_path = '' as $$
  select ((p_at at time zone p_timezone) - (p_day_starts_at - time '00:00'))::date
$$;

-- §4.1: the schedule version in force at p_at is the latest with effective_at <= p_at; without
-- one, the default schedule (Asia/Ho_Chi_Minh, 04:00 — decision 5). Security invoker: a learner
-- only sees their own versions (RLS), so for anyone else it answers with the default.
-- plpgsql, not sql: Postgres 17 keeps a SQL function's plan for the rest of the transaction
-- wherever the caller keeps its expression state (the events trigger does), RLS filter included,
-- even after the role changes. A learner insert followed by a system insert for another user in
-- the same transaction then saw no versions. plpgsql plans live in the plan cache, which re-plans
-- when the role changes (030-events, section 2).
create or replace function public.user_local_day(p_user_id uuid, p_at timestamptz) returns date
language plpgsql stable set search_path = '' as $$
begin
  return coalesce(
    (
      select public.local_day(p_at, s.timezone, s.day_starts_at)
      from public.schedule_versions s
      where s.user_id = p_user_id and s.effective_at <= p_at
      order by s.effective_at desc
      limit 1
    ),
    public.local_day(p_at, 'Asia/Ho_Chi_Minh', time '04:00')
  );
end $$;

-- ---------------------------------------------------------------------------------------------
-- Tables (§4.1)
-- ---------------------------------------------------------------------------------------------

create table public.events (
  id uuid primary key,                                   -- generated by the client (idempotent retries)
  user_id uuid not null references public.profiles (id) on delete cascade,
  actor_id uuid not null,                                -- no FK: audit rows outlive the actor
  source text not null check (source in ('learner', 'system', 'bot', 'admin')),
  type text not null check (type ~ '^[a-z_]+\.[a-z_]+$'),
  occurred_at timestamptz not null default now(),
  local_day date not null,                               -- computed by the insert trigger, never input
  -- Length caps (fix round 1): a learner inserts directly, and the quota caps rows, not bytes.
  track_id text check (octet_length(track_id) <= 32),   -- the track-id pattern's maximum
  item_id text check (octet_length(item_id) <= 128),
  plan_id uuid,                                          -- FK to day_plans arrives in 4.9
  block_id text check (octet_length(block_id) <= 128),
  payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(payload) = 'object' and octet_length(payload::text) <= 2048),
  rules_version integer not null default public.rules_version() check (rules_version >= 1)
);
create index events_user_occurred_idx on public.events (user_id, occurred_at);
create index events_plan_idx on public.events (plan_id) where plan_id is not null;

create table public.event_quota (                        -- internal (§4.5): no learner access
  user_id uuid not null references public.profiles (id) on delete cascade,
  local_day date not null,
  count integer not null default 0,
  primary key (user_id, local_day)
);

-- ---------------------------------------------------------------------------------------------
-- Insert and update triggers (§4.5). Row triggers of one kind fire in name order, so
-- events_20_quota sees the source events_10_prepare forced.
-- ---------------------------------------------------------------------------------------------

-- Security invoker, so current_user is the inserting role: `authenticated` for a direct insert or
-- apply_event (security invoker), the owner for a SECURITY DEFINER function such as
-- apply_system_event. For `authenticated`: only their own user_id — checked here, before the quota
-- trigger touches another user's counter (RLS would reject the row only after both triggers ran,
-- and a nonexistent user_id would surface as a foreign-key error from event_quota) — and only
-- learner types; actor_id, source, occurred_at and rules_version are forced. For every insert:
-- actor_id defaults to user_id, and local_day is computed here — never taken from input.
create function public.events_prepare() returns trigger
language plpgsql set search_path = '' as $$
begin
  if current_user = 'authenticated' then
    if new.user_id is distinct from auth.uid() then
      raise exception 'forbidden_user_id' using errcode = '42501';
    end if;
    if not new.type = any (public.learner_event_types()) then
      raise exception 'forbidden_event_type' using errcode = '42501';
    end if;
    new.actor_id := auth.uid();
    new.source := 'learner';
    new.occurred_at := now();
    new.rules_version := public.rules_version();
  end if;
  new.actor_id := coalesce(new.actor_id, new.user_id);
  new.local_day := public.user_local_day(new.user_id, new.occurred_at);
  return new;
end $$;

create trigger events_10_prepare before insert on public.events
  for each row execute function public.events_prepare();

-- SECURITY DEFINER, so a direct insert cannot bypass it and learners need no access to
-- event_quota. The upsert takes the row lock on (user_id, local_day), which serialises concurrent
-- inserts for that user-day; no count(*). A failed insert rolls its increment back with it.
-- System, bot and admin events are not counted.
create function public.events_enforce_quota() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_count integer;
begin
  if new.source = 'learner' then
    insert into public.event_quota (user_id, local_day, count)
    values (new.user_id, new.local_day, 1)
    on conflict (user_id, local_day) do update set count = event_quota.count + 1
    returning count into v_count;
    if v_count > 500 then
      raise exception 'quota_exceeded' using errcode = 'P0001';
    end if;
  end if;
  return new;
end $$;

create trigger events_20_quota before insert on public.events
  for each row execute function public.events_enforce_quota();

-- Append-only for every role. Rows are deleted only by the account-deletion cascade (and, once it
-- exists, the compaction job — §4.7).
create function public.events_reject_update() returns trigger
language plpgsql set search_path = '' as $$
begin
  raise exception 'events_are_append_only';
end $$;

create trigger events_append_only before update on public.events
  for each row execute function public.events_reject_update();

-- ---------------------------------------------------------------------------------------------
-- Function privileges: the events trigger and the rules_version column default run as the
-- inserting user, so authenticated may call the four helpers. Trigger functions get no grants.
-- ---------------------------------------------------------------------------------------------

revoke execute on function
  public.events_prepare(),
  public.events_enforce_quota(),
  public.events_reject_update()
from public, anon, authenticated;

revoke execute on function
  public.rules_version(),
  public.learner_event_types(),
  public.local_day(timestamptz, text, time),
  public.user_local_day(uuid, timestamptz)
from public, anon, authenticated;
grant execute on function
  public.rules_version(),
  public.learner_event_types(),
  public.local_day(timestamptz, text, time),
  public.user_local_day(uuid, timestamptz)
to authenticated, service_role;

-- ---------------------------------------------------------------------------------------------
-- Table privileges and RLS (§4.5): learners read and insert their own events while active;
-- event_quota has RLS on, no policies and no grants — only the quota trigger touches it.
-- ---------------------------------------------------------------------------------------------

revoke all on public.events, public.event_quota from anon, authenticated;
grant select, insert on public.events to authenticated;

alter table public.events enable row level security;
alter table public.event_quota enable row level security;

create policy events_select_own on public.events
  for select to authenticated
  using (user_id = (select auth.uid()));
create policy events_insert_own on public.events
  for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_active()));
