/**
 * Renders the [RF-1] parity test: SQL `public.local_day` must equal TypeScript `localDay` on the
 * shared fixtures (`lib/domain/time/fixtures.ts`, platform design §4.5). `pnpm db:fixtures`
 * (`local-day-parity-cli.ts`) writes the result; `local-day-parity.test.ts` fails when the
 * committed file is stale. This module only renders — importing it writes nothing.
 */
import type { DayStart, LocalDay } from '@/lib/domain/time/localDay'

export const LOCAL_DAY_PARITY_SQL_PATH = 'supabase/tests/database/020-local-day-parity.test.sql'

export type LocalDayFixture = {
  at: string
  timezone: string
  dayStartsAt: DayStart
  expected: LocalDay
  note: string
}

/** A SQL string literal (standard_conforming_strings: only `'` needs escaping). */
const literal = (value: string): string => `'${value.replaceAll("'", "''")}'`

/** The whole pgTAP file: one `select is(public.local_day(…), …)` per fixture. */
export function renderLocalDayParitySql(fixtures: readonly LocalDayFixture[]): string {
  const assertions = fixtures.map(
    (f) =>
      `select is(public.local_day(${literal(f.at)}::timestamptz, ${literal(f.timezone)}, ` +
      `${literal(f.dayStartsAt)}::time), ${literal(f.expected)}::date, ${literal(f.note)});`,
  )
  return [
    '-- Generated by `pnpm db:fixtures` from lib/domain/time/fixtures.ts. Do not edit by hand.',
    '-- [RF-1] parity: SQL public.local_day equals TypeScript localDay on the shared fixtures.',
    'begin;',
    'set client_min_messages = warning;',
    'create extension if not exists pgtap with schema extensions;',
    '',
    `select plan(${fixtures.length});`,
    '',
    ...assertions,
    '',
    'select * from finish();',
    'rollback;',
    '',
  ].join('\n')
}
